name: CI Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:

  # -------------------------
  # BUILD JOB
  # -------------------------
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build application
        run: |
          echo "Building application..."
          echo "Build completed successfully."


  # -------------------------
  # TEST JOB
  # -------------------------
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run tests
        run: |
          echo "Running tests..."
          echo "All tests passed successfully."


  # -------------------------
  # DOCKER BUILD JOB
  # -------------------------
  docker-build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build Docker image
        run: |
          docker build -t anmolpandit19/github-actions-practical:${{ github.sha }} .

      - name: Verify Docker image
        run: |
          docker images


  # -------------------------
  # DOCKER HUB PUSH JOB
  # -------------------------
  docker-push:
    runs-on: ubuntu-latest
    needs: docker-build

    # Push only when code is pushed to main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: anmolpandit19
          password: ${{ secrets.AMOLPANDIT19 }}

      - name: Build Docker image
        run: |
          docker build \
            -t anmolpandit19/github-actions-practical:latest \
            -t anmolpandit19/github-actions-practical:${{ github.sha }} .

      - name: Push Docker image to Docker Hub
        run: |
          docker push anmolpandit19/github-actions-practical:latest
          docker push anmolpandit19/github-actions-practical:${{ github.sha }}
